APP_NAME = "cartoview_arcgis_feature_server"

BASE_TPL = APP_NAME + "/base.html"
LAYER_LIST_TPL = APP_NAME + "/layer_list.html"
LAYER_LIST_ACTIONS_TPL = APP_NAME + "/layer_list_actions.html"
LAYER_EDIT_TPL = APP_NAME + "/layer_edit.html"
MAP_LIST_TPL = APP_NAME + "/map_list.html"
MAP_LIST_ACTIONS_TPL = APP_NAME + "/map_list_actions.html"
MAP_EDIT_TPL = APP_NAME + "/map_edit.html"
ITEM_DATA_JSON_TPL = APP_NAME + "/portal_json_config/item_data.json"
OPERATIONAL_LAYERS_JSON_TPL = APP_NAME + "/portal_json_config/operationalLayers.json"


LAYER_LIST_URL_NAME = APP_NAME + "_layer_list"
LAYER_EDIT_URL_NAME = APP_NAME + "_layer_edit"
MAP_LIST_URL_NAME = APP_NAME + "_map_list"
MAP_EDIT_URL_NAME = APP_NAME + "_map_edit"
MAP_PUBLISH_URL_NAME = APP_NAME + "_map_publish"
MAP_CONFIG_SAVE_URL_NAME = APP_NAME + "_map_config_save"
MAP_CONFIG_RESET_URL_NAME = APP_NAME + "_map_config_rest"